server:
  port: 8081
spring:
  application:
    name: clientMicroservice
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: libOnboardingClient
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
logging:
  level:
    root: INFO
    org:
      hibernate: WARN
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

flyway:
  enabled: true
  out-of-order: true
  locations: classpath:db/migration/oracle

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka